pr: 'none'

jobs:
  - job: Test
    strategy:
      matrix:
        running cmdlets from Windows 2019:
          imageName: windows-2019
        running cmdlets from Windows 2016:
          imageName: vs2017-win2016
    pool:
      vmImage: $(imageName)
    steps:
      - task: PowerShell@2
        displayName: Install modules
        inputs:
          pwsh: false
          targetType: inline
          failOnStderr: true
          script: |
            $modules = (Import-PowerShellDataFile "$env:BUILD_SOURCESDIRECTORY/src/BaselineManagement.psd1").RequiredModules
            $modules += @('PSScriptAnalyzer')
            Install-Module -Name $modules -Repository 'PSGallery' -Force -Verbose
            Install-Module -Name Pester -RequiredVersion 4.10.0 -Force -AllowClobber -SkipPublisherCheck -Verbose
      - task: PowerShell@2
        displayName: Pester unit tests
        inputs:
          pwsh: false
          targetType: inline
          script: |
            Import-module -Name Pester -RequiredVersion 4.10.0 -Force
            $Pester = Invoke-Pester -outputformat 'nunitxml' -outputfile "testResults.xml" -passthru
            exit $Pester.FailedCount
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: '**/testResults.xml'
        displayName: Publish test result
  - job: CodeSign
    dependsOn: Test
    pool:
      name: Package ES CodeHub Lab E
    steps:
      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection'
        inputs:
          failOnAlert: true
      - task: PkgESCodeSign@10
        displayName: 'CodeSign'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        inputs:
          signConfigXml: '$(Build.SourcesDirectory)\tools\SignConfig.xml'
          inPathRoot: '$(Build.SourcesDirectory)'
          outPathRoot: '$(Build.ArtifactStagingDirectory)\BaselineManagement'
      - task: PublishBuildArtifacts@1
        displayName: Publish artifact
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)\BaselineManagement'
          artifactName: BaselineManagement
